### PR TITLE
Fixed gitignore. Implemented local multiplayer

### LINKED ISSUE #2: Investigate if online is a possibility
- [x] Check Multiplayer HLAPI/Network Manager

### PR DESCRIPTION
**Pull request by EriksAire**
- Changed player controls to allow client - server handshake 
- Added netcode package 
- Added simple menu

### CODE REVIEW

File: Assets/Scripts/NetworkUI.cs [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+            {
+                print("Client NOT started");
+            }
+        });
+    }
+
+    private void OnSuccessConnection()
+    {
+        buttonsPanel.SetActive(false);
+        //menuCamera.SetActive(false);
```
Comment (nikkip98) [inline Assets/Scripts/NetworkUI.cs]: ?

Comment (EriksAire) [reply Assets/Scripts/NetworkUI.cs]: Resolved
